# Setup
title:               errdisabled.net
tagline:             'A networking site'
description:         'Work in progress..'
url:                 http://http://errdisabled.net/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Robert Kain
  url:               https://twitter.com/mdo
  email:             robertkain@pm.me

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
